export const WORLD_WIDTH = 1280;
export const WORLD_HEIGHT = 720;

export const SIMULATION_TUNING = {
  antCount: 50,
  spawnWidth: 220,
  fixedTimeStep: 1 / 30,
  maxDeltaTime: 1 / 20,
  linearDamping: 0.82,
  boundaryMargin: 48,
  groundY: WORLD_HEIGHT - 90,
  groundBandHeight: 24,
  queenPosition: {
    x: 108,
    y: WORLD_HEIGHT - 106,
  },
  exitPosition: {
    x: WORLD_WIDTH - 122,
    y: 114,
  },
};

export const ANT_TUNING = {
  spriteWidth: 56,
  spriteHeight: 56,
  maxSpeed: 46,
  forwardDrive: 60,
  postureDurationMin: 1.4,
  postureDurationMax: 3.2,
  collisionRadius: 11,
  supportHeight: 26,
  supportHalfWidth: 12,
  climbSpeed: 58,
  climbIntentThreshold: 0.18,
  climbHorizontalRange: 22,
  supportSnapDistance: 3,
  collapseScatterStepX: 18,
  collapseScatterStepY: 14,
  gravity: 320,
  maxFallSpeed: 220,
  maxSafeFallDistance: WORLD_HEIGHT * 0.5,
  maxConnections: 4,
  graspVerticalTolerance: 2.6,
  graspHorizontalTolerance: 5.6,
  graspCoverageRatio: 2 / 3,
  graspPollMinNeighbors: 1,
  graspPollMaxNeighbors: 4,
  graspNeighborRadiusX: 34,
  graspNeighborRadiusY: 24,
  graspHardRejectThreshold: 0.12,
  graspSuccessThresholdPerAnt: 0.5,
  graspHoldThreshold: 0.35,
  graspThrillBoostMin: 0.08,
  graspThrillBoostMax: 0.22,
  graspThrillDecayPerSecond: 0.08,
  graspPollCooldownMin: 0.40,
  graspPollCooldownMax: 1.4,
  graspLegSlotCount: 4,
  wallAnchorReachX: 18,
  wallAnchorReachY: 34,
  groundAnchorOffsetX: 10,
  wallAnchorOffsetY: 10,
  extraAnchorSpreadX: 8,
  maxBounceCount: 5,
  tumbleBounceSpeedX: 72,
  tumbleBounceSpeedY: 138,
  visualStateCycle: ["standing", "walking", "reaching", "walking", "grasping"],
  animationTickRate: 12,
  animationFps: {
    standing: 2.4,
    walking: 7.5,
    reaching: 4.2,
    grasping: 2.2,
  },
};

export const PHYSICS_TUNING = {
  attachedGravityScale: 0.6,
  attachedLinearDamping: 0.93,
  solverIterations: 5,
  legRestLength: 18,
  legRestLengthVariance: 4,
  legStiffness: 0.36,
  legDamping: 0.18,
  legAngularBias: 0.24,
  legAnchorPull: 0.48,
  legBreakStretchRatio: 1.8,
  legBreakDistanceBuffer: 10,
  positionCorrectionFactor: 0.42,
  impactBounceFactor: 0.52,
  impactTransferFactor: 0.24,
  impactHorizontalJitter: 34,
  supportRideFollow: 0.72,
  supportRideVerticalSnap: 0.42,
  microVelocityClamp: 140,
};

export const SENSOR_TUNING = {
  wedgeCount: 6,
  raysPerWedge: 3,
  maxDistance: 110,
  debugAntIndex: 0,
  spatialHashCellSize: 96,
  scalarInputCount: 2,
  wedgeCenters: [
    (5 * Math.PI) / 3,
    0,
    Math.PI / 3,
    (2 * Math.PI) / 3,
    Math.PI,
    (4 * Math.PI) / 3,
  ],
  wedgeNames: ["one", "three", "five", "seven", "nine", "eleven"],
  borderRayTallyWeight: 1,
  centerRayTallyWeight: 4,
  colorRange: {
    food: 1,
    queen: 0.45,
    ant: -0.1,
    obstacle: -0.65,
  },
  localFoodScentRange: 220,
  antSenseRadius: 10,
  queenSenseRadius: 20,
  localAntQueryPadding: 16,
};

export const NEURAL_TUNING = {
  inputCount: SENSOR_TUNING.wedgeCount * 2 + SENSOR_TUNING.scalarInputCount,
  hiddenLayers: [12],
  outputCount: 4,
  xVelOutputIndex: 0,
  yVelOutputIndex: 1,
  graspOutputIndex: 2,
  interactionOutputIndex: 3,
};

export const MAP_TUNING = {
  groundColor: 0xd0ae79,
  wallColor: 0x9d7749,
  pegColor: 0x7a5632,
  foodColor: 0x4f8a3b,
  queenColor: 0x8d2a1e,
};
